title: Commonhaus Foundation
description: > # this means to ignore newlines until the next tag
  The Commonhaus Foundation is dedicated to nurturing and sustaining GitHub-style
  open-source projects through community-driven collaboration and shared stewardship.
  We unite developers, contributors, and users in a dynamic ecosystem, focusing on
  the long-term growth and stability of essential open-source libraries and frameworks
  without the overhead of traditional governance models.
disableLiveReload: true
disablePathToLower: true
frontmatter:
  date:
    - :git
    - :default
languageCode: en-us
publishDir: "../public"
uglyURLs: true
params:
  render_hooks:
    link:
      errorLevel: 'warning'
markup:
  defaultMarkdownHandler: goldmark
module:
  mounts:
  - source: ../foundation/governance
    includeFiles: '*.md'
    target: content/governance
  - source: ../foundation/
    includeFiles: '*.md'
    target: content
  - source: content
    target: content
  - source: ../foundation/
    includeFiles: '*.yaml'
    target: data