name: update-metadata

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '47 21 * * 3'

  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read

env:
  GH_BOT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GH_BOT_NAME: "GitHub Action"
  DENO_DIR: .deno-cache
  REPO: commonhaus/commonhaus.github.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: "push-content"
      cancel-in-progress: true
    steps:
      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Git Config
        run: |
          git config user.name ${{ env.GH_BOT_NAME }}
          git config user.email ${{ env.GH_BOT_EMAIL }}

      - name: Contact information update
        env:
          GH_TOKEN: ${{ secrets.WEB_REPO_READ }}
        run: |
          deno task about
          git add -A -- ./site/_data/about.yml
          if git diff --quiet HEAD; then
            echo "-- No changes -- "
          else
            git commit -am "👥 Auto-update contact metadata" && git push
          fi

      - name: Sleep for 30 seconds (wait a bit before queueing the next job)
        run: sleep 30s
        shell: bash

  publish-gh-pages:
    needs: build
    uses: ./.github/workflows/gh-pages.yml
    concurrency:
      group: "pages"
      cancel-in-progress: true
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit
